### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Vendicated** [Vencord/Vesktop#324]
This is not really a direct roadmap, mostly just tracking features that are planned

- [ ] Implement global keybinds
- [ ] Get rid of the update prompt
  - [ ] Auto update on Windows via electron autoupdater
  - [ ] Disable entirely on Linux. Auto updating will be done via flatpak / package manager (set up apt/rpm repo?)
  - [ ] Likely disable entirely on Mac. OR, steal someone's code signing certificate and use auto updating
- Maybe use [screencapturekit](https://developer.apple.com/documentation/screencapturekit/) for audio screen sharing on mac
- [ ] implement autostart for flatpak
- [ ] add (auto)start minimised
- [ ] reorganise settings to not be a crazy mess of switches (either use sections, or even multiple settings tabs)
- [ ] improve description & vesktop branding. create vesktop website & advertise on vencord.dev

**Comment by devxan** [comment]
Reorganizing the settings sounds awesome 🔥

**Comment by Curve** [comment]
> set up apt/rpm repo?

Supporting a dozen package manager is going to quickly turn into a mess, I'd actually recommend just supplying the flatpak - It'll probably be the most stable experience for anyone.

RPM / DEB and so on could still be handled by the community

**Comment by justin13888** [comment]
I love your work @Vendicated! Curious whether we could contribute some of these features you've listed. For context, I use Vesktop on Linux so I could perhaps see if I could implement any of the Linux features?

**Comment by Vendicated** [comment]
Yes you can, contributions are always Welcome! Out of the ones listed here, a lot of them are already being done, but you could contribute any of the last 3

Or take a look at the open issues and see if there's any bug or feature request you would like to fix or implement

**Comment by justin13888** [comment]
Sounds good!

**Comment by justin13888** [comment]
@Vendicated For the vesktop website, I was wondering if you'd like a website similar to the existing one on https://vencord.dev/?

**Comment by Tresillo2017** [comment]
I have a problem where desktop audio lower down while someone is talking, I guess is discord default but i can't seem to find it on the settings. 

The other things is auto voice gain, since there are two option Voice Activity, Push to talk, and voice activity has a fixed threshold while on the official desktop is automatic.

**Comment by Vendicated** [comment]
> For the vesktop website, I was wondering if you'd like a website similar to the existing one on https://vencord.dev/?

correct, that would require contributions to the [vencord.dev](https://github.com/Vencord/vencord.dev) repo

> does it only pertain to "Vesktop Settings" page or other settings too?

only the vesktop settings section. currently it's a crazy mess of switches which is a bit hard to use

**Comment by justin13888** [comment]
@Vendicated I've created a ticket to track progress on adding Vesktop info to vencord.dev: https://github.com/Vencord/vencord.dev/issues/39

Will continue discussions about it on there instead

**Comment by sherichev** [comment]
So nice! I really appreciate your work on it!

**Comment by justin13888** [comment]
@Vendicated I've also created an issue and PR for the improved Vesktop settings: https://github.com/Vencord/Vesktop/issues/378

**Comment by pktiuk** [comment]
In case of PPA for Debian based maybe using makedeb can be a solution https://mpr.makedeb.org

**Comment by V0ID-Whisperer** [comment]
For flatplak auto start could just add a this ``flatpak run dev.vencord.Vesktop`` to startup apps or smth

**Comment by Vendicated** [comment]
that works but it's not possible to do this from within the flatpak. instead there's a portal for it, which i already got working in #282

**Comment by pointydev** [comment]
> * Disable entirely on Linux. Auto updating will be done via flatpak / package manager (set up apt/rpm repo?)

For distributing the rpm outside of direct downloads, you could either:
- Build on [Copr](https://copr.fedorainfracloud.org/)
- Submit to [Terra](https://terra.fyralabs.com/)
- Set up your own repo

**Comment by ShinyGil** [comment]
> > * Disable entirely on Linux. Auto updating will be done via flatpak / package manager (set up apt/rpm repo?)
> 
> For distributing the rpm outside of direct downloads, you could either:
> 
> * Build on [Copr](https://copr.fedorainfracloud.org/)
> * Submit to [Terra](https://terra.fyralabs.com/)
> * Set up your own repo

Seconding COPR. It makes builds quite a bit easier and distribution is as simple as enabling the single repo. Huge fan of it.

**Comment by Alyxx88** [comment]
Any plans to implement game detection? I can't get aRPC reliably working.

**Comment by Vendicated** [comment]
arrpc is already integrated natively.

**Comment by Asyrie** [comment]
Discord seems to have an option to set a webcam/another audio source as screenshare, atleast on windows, any plans to bring to to Vesktop on linux/mac? Useful for capture cards/OBS

**Comment by AlphaCraft9658** [comment]
Is there any current progress on the VolumeBooster Plugin for Vesktop?

**Comment by charitarthchugh** [comment]
For anyone using Gnome and wants to autostart with the Flatpak version of Vesktop, adding Vesktop to the startup applications in Gnome Tweaks works quite well.

**Comment by shvedes** [comment]
> add (auto)start minimised

But it works already with `--start-minimized`. Or i missing something?

**Comment by AtelierSnek** [comment]
By the by, are you looking for any contributions for this? I can take a look at the auto-update and volume stuff potentially.

**Comment by EinsKatze** [comment]
Looking forward to Global Keybinds,
Keybinds for muting and co are useful ngl

**Comment by jojommeke** [comment]
does global keybinds also mean push to talk?

**Comment by rathmerdominik** [comment]
I am not even sure if wlroots already supports Global keybinds :thinking: 
I think all the others do... But sucks for my SwayWM setup

**Comment by atchimgripo** [comment]
could you please focus a bit more on the >100% volume? I really like vesktop but I just can't use it because of that, everyone sounds too quiet and there's no way to tune their volume

**Comment by AtelierSnek** [comment]
> I am not even sure if wlroots already supports Global keybinds 🤔 I think all the others do... But sucks for my SwayWM setup

As far as I understand, Global keybinds don't exist in Wayland in the general case, since allowing a program to gather global input violates the security model.

Either way, the canonical way to do this is to create a DBUS or CLI interface that can receive input and use the WM (so for sway, the sway config file, likely via some `bindsym` option) to dispatch something to them. Which, sucks, but it's a way forward.

> could you please focus a bit more on the >100% volume? I really like vesktop but I just can't use it because of that, everyone sounds too quiet and there's no way to tune their volume

Hoping work clears up a bit soon so I can look at this. It's still sitting on the backlog on my end.

**Comment by Vendicated** [comment]
> As far as I understand, Global keybinds don't exist in Wayland

Usually libraries / programs just register a global key listener for keybinds. However, wayland doesn't allow that for privacy reasons, programs only get keystrokes if they are focused

However, there is a portal in the works for keybinds: https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.GlobalShortcuts.xml

But it isn't implemented in all desktop environments

further discussions aboit keybinds should go in https://github.com/Vencord/Vesktop/issues/18

**Comment by Macaquinyo** [comment]
> > add (auto)start minimised
> 
> But it works already with `--start-minimized`. Or i missing something?

This. I just added the flag to the autostart script and vesktop starts minimized.  

After checking "start with system" in options, a toggle could appear that switches the autostart script between 
"/usr/lib/electron31/electron" "/usr/lib/vesktop/app.asar"
and
"/usr/lib/electron31/electron" "/usr/lib/vesktop/app.asar" --start-minimized
it should be trivial to implement. ¿Maybe something similar could be done in windows?

**Comment by ZirixCZ** [comment]
@atchimgripo , @AtelierSnek The >100% volume feature has an open PR here: https://github.com/Vendicated/Vencord/pull/2730

**Comment by TheInfamousAlk** [comment]
Can we also have "zoom level" from the native discord appearance settings? It's a bit squished on my monitor if I can't lower that. 

Discord:
![image](https://github.com/user-attachments/assets/5fccbd0e-629d-4a58-b612-9e0d61ec3bec)

Vencord:
![image](https://github.com/user-attachments/assets/f6176417-b05c-46d6-9dee-4a4967d7c6b2)

**Comment by ImLvna** [comment]
You can still use Ctrl+Plus or Ctrl+Minus to edit that

**Comment by TheInfamousAlk** [comment]
Didn't realize I could do that in the first place, thanks! That, plus not being able to use my mouse button to push to talk are the only things keeping from switching. It would probably help to also have it in the menu for people who don't know that keybind.

**Comment by solaluset** [comment]
@ImLvna hi. Unfortunately this does not work for me. I'm on Void Linux.
